version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build || echo "No build script"

artifacts:
  files:
    - server.js
    - package.json
    - package-lock.json
    - src/**/*
    - routes/**/*
    - .env  # optional, but recommended to use Secrets Manager instead
